# Generated by Django 4.1 on 2023-06-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_deliverychellan_challanitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
