# Generated by Django 4.1 on 2023-06-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0018_alter_unit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='user',
            new_name='user_id',
        ),
    ]
