# Generated by Django 4.1 on 2023-06-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0019_rename_user_unit_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='user_id',
            new_name='user',
        ),
    ]
