# Generated by Django 4.1 on 2023-06-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0022_unit_additem_unit_vendor_table_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_table',
            name='unit',
        ),
    ]
