# Generated by Django 4.1 on 2023-06-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0027_alter_recurring_bills_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
